### ISSUE TITLE
Problem with split --header with descriptive headers

### ISSUE THREAD

**Issue by osallou** [brentp/pyfasta#8]
We use pyfasta to split multi fasta files in one file per sequence.
However it fails with some descriptive header.

As you can see below, it tries to create a file with header name, but header name is:
gi|34881901|ref|NW_048060.1| Rattus norvegicus strain BN/SsNHsdMCW chromosome X unlocalized genomic scaffold, RGSC_v3.4.fasta

which does not fit as a filename.

Either seqid should be correctly extracted from header, either regexp should propose a "%(inc)" to create an increment on each file name (keeping original header in the file).

pyfasta split --header '%(seqid)s.fasta

Here is error log:
Traceback (most recent call last):
  File "/softs/local/stan/new_2011/stan", line 104, in <module>
    raise IOError(err)
IOError: Traceback (most recent call last):
  File "/local/python/2.7/bin/pyfasta", line 8, in <module>
    load_entry_point('pyfasta==0.4.1', 'console_scripts', 'pyfasta')()
  File
"/local/python/2.7/lib/python2.7/site-packages/pyfasta-0.4.1-py2.7.egg/pyfasta/**init**.py",
line 37, in main
    globals()[action](sys.argv[2:])
  File
"/local/python/2.7/lib/python2.7/site-packages/pyfasta-0.4.1-py2.7.egg/pyfasta/split_fasta.py",
line 117, in split
    return with_header_names(f, names)
  File
"/local/python/2.7/lib/python2.7/site-packages/pyfasta-0.4.1-py2.7.egg/pyfasta/split_fasta.py",
line 133, in with_header_names
    fh = open(name, 'wb')
IOError: [Errno 2] No such file or directory: 'gi|34881901|ref|NW_048060.1| Rattus
norvegicus strain BN/SsNHsdMCW chromosome X unlocalized genomic scaffold, RGSC_v3.4.fasta'

**Comment by brentp** [comment]
I think `%(inc)d` would be a good way to handle this. I'll have a look next week (or gladly accept a pull-request/patch that implements).

**Comment by osallou** [comment]
The patch I have is quite ugly. I am not expert in python. The impact code in split_fasta.py is

```
if options.header:
    names = dict([(seqid, options.header % \
                  dict(fasta=f.fasta_name, seqid=seqid)) \
                                   for seqid in f.keys()])
```

I do not know if we could manage a seqid AND an inc within a range [ range(len(f.keys)) ], in this definition.
Personally I added here a string constant for %(inc) and replace it in a second step with a counter.

You really may put a better code.

However, if you really wish it, I create fork/patch/pull-request.....

**Comment by brentp** [comment]
won't this do it?

``` python

if options.header:
    names = dict([(seqid, options.header % \
                  dict(fasta=f.fasta_name, seqid=seqid, inc=i)) \
                                   for i, seqid in enumerate(f.keys())])
```

**Comment by osallou** [comment]
May  be
As i said i am not a python expert... ;-)
But it looks fine
Le 24 mai 2012 19:17, "Brent Pedersen - Bioinformatics" <
reply@reply.github.com>
a écrit :
